In [ ]:
%load_ext autoreload
%autoreload 2
import yfinance as yf
import pandas as pd
import numpy as np

In [2]:
from backtest.dataModule import DataSource, DataModule

In [3]:
dataSource = DataSource("yfinance", "historical", ["MSFT", "AAPL", "NVDA"])
dataModule = DataModule(dataSource)

In [10]:
yf.Ticker('MSFT').history()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-08-26 00:00:00-04:00,487.850006,497.399994,487.309998,496.369995,20758900,0.0,0.0
2026-08-27 00:00:00-04:00,494.880005,506.480011,490.079987,505.059998,28688800,0.0,0.0
2026-08-28 00:00:00-04:00,505.329987,517.780029,504.869995,513.530029,29207300,0.0,0.0
2026-08-31 00:00:00-04:00,510.380005,512.190002,506.390015,507.290009,27208900,0.0,0.0
2026-09-01 00:00:00-04:00,497.519989,505.970001,496.779999,501.019989,21046900,0.0,0.0
2026-09-02 00:00:00-04:00,499.850006,500.269989,493.809998,496.820007,15336100,0.0,0.0
2026-09-03 00:00:00-04:00,501.660004,515.650024,500.799988,510.119995,24125900,0.0,0.0
2026-09-04 00:00:00-04:00,510.000000,511.000000,499.359985,499.700012,18101800,0.0,0.0
2026-09-08 00:00:00-04:00,493.010010,495.190002,490.149994,493.950012,18882300,0.0,0.0
2026-09-09 00:00:00-04:00,493.070007,494.390015,489.799988,491.649994,12889600,0.0,0.0
2026-09-10 00:00:00-04:00,488.320007,494.519989,486.000000,492.440002,16038800,0.0,0.0
2026-09-11 00:00:00-04:00,495.649994,498.970001,492.579987,495.630005,14510500,0.0,0.0
2026-09-14 00:00:00-04:00,497.059998,509.950012,495.339996,505.410004,23091900,0.0,0.0
2026-09-15 00:00:00-04:00,500.059998,505.899994,495.540009,497.119995,17794600,0.0,0.0
2026-09-16 00:00:00-04:00,493.029999,495.970001,487.230011,490.299988,16670300,0.0,0.0
2026-09-17 00:00:00-04:00,497.799988,501.470001,493.170013,497.750000,17841600,0.0,0.0
2026-09-18 00:00:00-04:00,497.970001,498.649994,491.100006,493.779999,39622300,0.0,0.0
2026-09-21 00:00:00-04:00,494.950012,501.869995,491.329987,501.609985,27959900,0.0,0.0
2026-09-22 00:00:00-04:00,507.320007,508.500000,493.649994,498.000000,21652800,0.0,0.0
2026-09-23 00:00:00-04:00,500.760010,509.440002,495.880005,500.589996,19445600,0.0,0.0
2026-09-24 00:00:00-04:00,495.070007,498.899994,491.220001,497.929993,16657600,0.0,0.0
2026-09-25 00:00:00-04:00,NaN,NaN,NaN,NaN,37985485,0.0,0.0

In [4]:
test_df = dataModule.load("2020-01-01", "2022-12-31", "1d")

Fetching yfinance price data

/Users/main/Desktop/python-quant/backtest/dataModule.py:34: FutureWarning: YF.download() has changed argument auto_adjust default to True
  raw = yf.download(tickers=self.dataSource.yfTickers,
[*********************100%***********************]  3 of 3 completed

In [5]:
test_df

                        close        high         low        open     volume
date       ticker
2020-01-02 AAPL     72.271538   72.331694   71.029915   71.282568  135480400
           MSFT    151.544281  151.648066  149.383682  149.808252   22622100
           NVDA      5.957137    5.957137    5.877927    5.928333  237536000
2020-01-03 AAPL     71.568932   72.326897   71.345153   71.501557  146322800
           MSFT    149.657272  150.912123  149.128917  149.374235   21116200
...                       ...         ...         ...         ...        ...
2022-12-29 MSFT    233.898361  234.781513  228.696522  228.696522   19770700
           NVDA     14.554338   14.634072   14.179592   14.354009  354923000
2022-12-30 AAPL    127.651535  127.671189  125.195383  126.158201   77034200
           MSFT    232.743484  232.879353  229.676725  231.180991   21938500
           NVDA     14.565303   14.580252   14.185572   14.286235  310490000

[2268 rows x 5 columns]

In [2]:
dat = yf.Ticker("MSFT")

In [9]:
data = yf.download(["MSFT", "NVDA"])

/var/folders/g0/24qwcrld4nb_zw_4mfnl5n240000gn/T/ipykernel_80324/1174321684.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(["MSFT", "NVDA"])
[*********************100%***********************]  2 of 2 completed

In [10]:
data

Price            Close                    High                     Low  \
Ticker            MSFT        NVDA        MSFT        NVDA        MSFT
Date
2026-08-26  496.369995  209.425659  497.399994  213.361258  487.309998
2026-08-27  505.059998  227.725174  506.480011  230.212396  490.079987
2026-08-28  513.530029  217.306839  517.780029  229.003742  504.869995
2026-08-31  507.290009  220.533234  512.190002  221.052657  506.390015
2026-09-01  501.019989  217.196976  505.970001  220.163657  496.779999
2026-09-02  496.820007  224.159180  500.269989  227.695216  493.809998
2026-09-03  510.119995  228.194656  515.650024  230.142474  500.799988
2026-09-04  499.700012  230.102524  511.000000  234.497600  499.359985
2026-09-08  493.950012  225.477692  495.190002  233.448783  490.149994
2026-09-09  491.649994  223.419998  494.390015  225.927187  489.799988
2026-09-10  492.440002  218.360001  494.519989  220.990005  486.000000
2026-09-11  495.630005  218.289993  498.970001  222.000000  492.579987
2026-09-14  505.410004  210.960007  509.950012  212.770004  495.339996
2026-09-15  497.119995  212.169998  505.899994  213.940002  495.540009
2026-09-16  490.299988  213.899994  495.970001  216.759995  487.230011
2026-09-17  497.750000  219.339996  501.470001  219.910004  493.170013
2026-09-18  493.779999  222.270004  498.649994  222.729996  491.100006
2026-09-21  501.609985  227.380005  501.869995  228.500000  491.329987
2026-09-22  498.000000  228.869995  508.500000  229.979996  493.649994
2026-09-23  500.589996  225.509995  509.440002  228.949997  495.880005
2026-09-24  497.929993  224.580002  498.899994  224.940002  491.220001
2026-09-25         NaN         NaN         NaN         NaN         NaN

Price                         Open                Volume
Ticker            NVDA        MSFT        NVDA      MSFT       NVDA
Date
2026-08-26  208.996132  487.850006  212.402324  20758900  179900000
2026-08-27  220.653086  494.880005  222.610902  28688800  298909800
2026-08-28  216.567661  505.329987  227.105872  29207300  195116400
2026-08-31  215.968349  510.380005  218.625365  27208900  124702700
2026-09-01  214.859595  497.519989  216.507744  21046900  109756200
2026-09-02  218.235800  499.850006  218.545451  15336100  157104700
2026-09-03  224.498795  501.660004  225.767380  24125900  134681600
2026-09-04  229.373344  510.000000  230.831704  18101800  135352400
2026-09-08  224.598686  493.010010  232.849448  18882300  122965600
2026-09-09  223.210241  493.070007  225.028199  12889600   82955500
2026-09-10  217.199997  488.320007  220.529999  16038800  105768000
2026-09-11  218.149994  495.649994  221.240005  14510500   89060100
2026-09-14  208.929993  497.059998  211.240005  23091900  132267200
2026-09-15  211.160004  500.059998  213.380005  17794600   88059700
2026-09-16  212.500000  493.029999  214.139999  16670300   96563600
2026-09-17  217.149994  497.799988  218.380005  17841600   94191300
2026-09-18  218.029999  497.970001  219.350006  39622300  190287400
2026-09-21  221.559998  494.950012  222.940002  27959900  109806100
2026-09-22  226.500000  507.320007  226.850006  21652800   95746700
2026-09-23  224.020004  500.760010  228.029999  19445600   89547300
2026-09-24  221.089996  495.070007  222.080002  16657600   77469900
2026-09-25         NaN         NaN         NaN  37985485   87931936

In [11]:
data = data.stack(future_stack=True)

In [12]:
data.index.names = ['date', 'ticker']
data

Price                   Close        High         Low        Open     Volume
date       ticker
2026-08-26 MSFT    496.369995  497.399994  487.309998  487.850006   20758900
           NVDA    209.425659  213.361258  208.996132  212.402324  179900000
2026-08-27 MSFT    505.059998  506.480011  490.079987  494.880005   28688800
           NVDA    227.725174  230.212396  220.653086  222.610902  298909800
2026-08-28 MSFT    513.530029  517.780029  504.869995  505.329987   29207300
           NVDA    217.306839  229.003742  216.567661  227.105872  195116400
2026-08-31 MSFT    507.290009  512.190002  506.390015  510.380005   27208900
           NVDA    220.533234  221.052657  215.968349  218.625365  124702700
2026-09-01 MSFT    501.019989  505.970001  496.779999  497.519989   21046900
           NVDA    217.196976  220.163657  214.859595  216.507744  109756200
2026-09-02 MSFT    496.820007  500.269989  493.809998  499.850006   15336100
           NVDA    224.159180  227.695216  218.235800  218.545451  157104700
2026-09-03 MSFT    510.119995  515.650024  500.799988  501.660004   24125900
           NVDA    228.194656  230.142474  224.498795  225.767380  134681600
2026-09-04 MSFT    499.700012  511.000000  499.359985  510.000000   18101800
           NVDA    230.102524  234.497600  229.373344  230.831704  135352400
2026-09-08 MSFT    493.950012  495.190002  490.149994  493.010010   18882300
           NVDA    225.477692  233.448783  224.598686  232.849448  122965600
2026-09-09 MSFT    491.649994  494.390015  489.799988  493.070007   12889600
           NVDA    223.419998  225.927187  223.210241  225.028199   82955500
2026-09-10 MSFT    492.440002  494.519989  486.000000  488.320007   16038800
           NVDA    218.360001  220.990005  217.199997  220.529999  105768000
2026-09-11 MSFT    495.630005  498.970001  492.579987  495.649994   14510500
           NVDA    218.289993  222.000000  218.149994  221.240005   89060100
2026-09-14 MSFT    505.410004  509.950012  495.339996  497.059998   23091900
           NVDA    210.960007  212.770004  208.929993  211.240005  132267200
2026-09-15 MSFT    497.119995  505.899994  495.540009  500.059998   17794600
           NVDA    212.169998  213.940002  211.160004  213.380005   88059700
2026-09-16 MSFT    490.299988  495.970001  487.230011  493.029999   16670300
           NVDA    213.899994  216.759995  212.500000  214.139999   96563600
2026-09-17 MSFT    497.750000  501.470001  493.170013  497.799988   17841600
           NVDA    219.339996  219.910004  217.149994  218.380005   94191300
2026-09-18 MSFT    493.779999  498.649994  491.100006  497.970001   39622300
           NVDA    222.270004  222.729996  218.029999  219.350006  190287400
2026-09-21 MSFT    501.609985  501.869995  491.329987  494.950012   27959900
           NVDA    227.380005  228.500000  221.559998  222.940002  109806100
2026-09-22 MSFT    498.000000  508.500000  493.649994  507.320007   21652800
           NVDA    228.869995  229.979996  226.500000  226.850006   95746700
2026-09-23 MSFT    500.589996  509.440002  495.880005  500.760010   19445600
           NVDA    225.509995  228.949997  224.020004  228.029999   89547300
2026-09-24 MSFT    497.929993  498.899994  491.220001  495.070007   16657600
           NVDA    224.580002  224.940002  221.089996  222.080002   77469900
2026-09-25 MSFT           NaN         NaN         NaN         NaN   37985485
           NVDA           NaN         NaN         NaN         NaN   87931936

In [13]:
data.columns = [col.lower().replace(' ', '_') for col in data.columns]

In [14]:
data

                        close        high         low        open     volume
date       ticker
2026-08-26 MSFT    496.369995  497.399994  487.309998  487.850006   20758900
           NVDA    209.425659  213.361258  208.996132  212.402324  179900000
2026-08-27 MSFT    505.059998  506.480011  490.079987  494.880005   28688800
           NVDA    227.725174  230.212396  220.653086  222.610902  298909800
2026-08-28 MSFT    513.530029  517.780029  504.869995  505.329987   29207300
           NVDA    217.306839  229.003742  216.567661  227.105872  195116400
2026-08-31 MSFT    507.290009  512.190002  506.390015  510.380005   27208900
           NVDA    220.533234  221.052657  215.968349  218.625365  124702700
2026-09-01 MSFT    501.019989  505.970001  496.779999  497.519989   21046900
           NVDA    217.196976  220.163657  214.859595  216.507744  109756200
2026-09-02 MSFT    496.820007  500.269989  493.809998  499.850006   15336100
           NVDA    224.159180  227.695216  218.235800  218.545451  157104700
2026-09-03 MSFT    510.119995  515.650024  500.799988  501.660004   24125900
           NVDA    228.194656  230.142474  224.498795  225.767380  134681600
2026-09-04 MSFT    499.700012  511.000000  499.359985  510.000000   18101800
           NVDA    230.102524  234.497600  229.373344  230.831704  135352400
2026-09-08 MSFT    493.950012  495.190002  490.149994  493.010010   18882300
           NVDA    225.477692  233.448783  224.598686  232.849448  122965600
2026-09-09 MSFT    491.649994  494.390015  489.799988  493.070007   12889600
           NVDA    223.419998  225.927187  223.210241  225.028199   82955500
2026-09-10 MSFT    492.440002  494.519989  486.000000  488.320007   16038800
           NVDA    218.360001  220.990005  217.199997  220.529999  105768000
2026-09-11 MSFT    495.630005  498.970001  492.579987  495.649994   14510500
           NVDA    218.289993  222.000000  218.149994  221.240005   89060100
2026-09-14 MSFT    505.410004  509.950012  495.339996  497.059998   23091900
           NVDA    210.960007  212.770004  208.929993  211.240005  132267200
2026-09-15 MSFT    497.119995  505.899994  495.540009  500.059998   17794600
           NVDA    212.169998  213.940002  211.160004  213.380005   88059700
2026-09-16 MSFT    490.299988  495.970001  487.230011  493.029999   16670300
           NVDA    213.899994  216.759995  212.500000  214.139999   96563600
2026-09-17 MSFT    497.750000  501.470001  493.170013  497.799988   17841600
           NVDA    219.339996  219.910004  217.149994  218.380005   94191300
2026-09-18 MSFT    493.779999  498.649994  491.100006  497.970001   39622300
           NVDA    222.270004  222.729996  218.029999  219.350006  190287400
2026-09-21 MSFT    501.609985  501.869995  491.329987  494.950012   27959900
           NVDA    227.380005  228.500000  221.559998  222.940002  109806100
2026-09-22 MSFT    498.000000  508.500000  493.649994  507.320007   21652800
           NVDA    228.869995  229.979996  226.500000  226.850006   95746700
2026-09-23 MSFT    500.589996  509.440002  495.880005  500.760010   19445600
           NVDA    225.509995  228.949997  224.020004  228.029999   89547300
2026-09-24 MSFT    497.929993  498.899994  491.220001  495.070007   16657600
           NVDA    224.580002  224.940002  221.089996  222.080002   77469900
2026-09-25 MSFT           NaN         NaN         NaN         NaN   37985485
           NVDA           NaN         NaN         NaN         NaN   87931936

In [ ]:
data

Price            Close        High         Low        Open    Volume
Ticker            MSFT        MSFT        MSFT        MSFT      MSFT
Date
2026-08-26  496.369995  497.399994  487.309998  487.850006  20758900
2026-08-27  505.059998  506.480011  490.079987  494.880005  28688800
2026-08-28  513.530029  517.780029  504.869995  505.329987  29207300
2026-08-31  507.290009  512.190002  506.390015  510.380005  27208900
2026-09-01  501.019989  505.970001  496.779999  497.519989  21046900
2026-09-02  496.820007  500.269989  493.809998  499.850006  15336100
2026-09-03  510.119995  515.650024  500.799988  501.660004  24125900
2026-09-04  499.700012  511.000000  499.359985  510.000000  18101800
2026-09-08  493.950012  495.190002  490.149994  493.010010  18882300
2026-09-09  491.649994  494.390015  489.799988  493.070007  12889600
2026-09-10  492.440002  494.519989  486.000000  488.320007  16038800
2026-09-11  495.630005  498.970001  492.579987  495.649994  14510500
2026-09-14  505.410004  509.950012  495.339996  497.059998  23091900
2026-09-15  497.119995  505.899994  495.540009  500.059998  17794600
2026-09-16  490.299988  495.970001  487.230011  493.029999  16670300
2026-09-17  497.750000  501.470001  493.170013  497.799988  17841600
2026-09-18  493.779999  498.649994  491.100006  497.970001  39622300
2026-09-21  501.609985  501.869995  491.329987  494.950012  27959900
2026-09-22  498.000000  508.500000  493.649994  507.320007  21652800
2026-09-23  500.589996  509.440002  495.880005  500.760010  19445600
2026-09-24  497.929993  498.899994  491.220001  495.070007  16657600
2026-09-25         NaN         NaN         NaN         NaN  37985485